apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: 8081-8081
    port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: demo
  type: {{ .Values.service.port }}
status:
  loadBalancer: {}
